var manifest = [
	{src:'images/btn/1.png', id:''},
	{src:'images/box1_fps/1.png', id:''},
	{src:'images/box1_fps/2.png', id:''},
	{src:'images/box1_fps/3.png', id:''},
	{src:'images/box1_fps/bg.jpg', id:''},
	{src:'images/star.png', id:''},
	{src:'images/box1_text1.png', id:''},
	{src:'images/box1_text2.png', id:''},
	{src:'images/box1_text3.png', id:''},
	// {src:'music/bg1.mp3', id:'bg1'},
	// {src:'music/bg2.mp3', id:'bg2'},
	// {src:'music/box2_rotate.mp3', id:'box2_rotate'},
	// {src:'music/box3_rocket.mp3', id:'box3_rocket'},
	// {src:'music/box4_cow.mp3', id:'box4_cow'},
	// {src:'music/box5_com.mp3', id:'box5_com'},
	// {src:'music/box5_milk.mp3', id:'box5_milk'},
	// {src:'music/box6_rise.mp3', id:'box6_rise'},
	{src:'images/box2_fps/1.jpg', id:''},
	{src:'images/box2_fps/2.jpg', id:''},
	{src:'images/box2_fps/9.jpg', id:''},
	{src:'images/box2_fps/bg.jpg', id:''},
	{src:'images/box2_fps/box2_text1.png', id:''},
	{src:'images/box2_fps/box2_text2.png', id:''},
	{src:'images/box2_fps/dot.png', id:''},
	{src:'images/box2_fps/text.png', id:''},
	{src:'images/comm_bottom1.png', id:''},
	{src:'images/comm_box_bottom.png', id:''},
	{src:'images/comm_box_middle.png', id:''},
	{src:'images/comm_box_top.png', id:''},
	{src:'images/comm_light.png', id:''},
	{src:'images/comm_top.png', id:''},
	{src:'images/cover_bottom.png', id:''},
	{src:'images/cover_top.png', id:''},
	{src:'images/false_btn1.png', id:''},
	{src:'images/false_btn2.png', id:''},
];